# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Contributors to the Eclipse Foundation
# Assisted By: Codex (GPT-6 Sol High)

agent {
    data_dir = "/var/lib/spire/agent/.data"
    log_level = "INFO"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/run/spire/agent/public/api.sock"
    trust_bundle_path = "/etc/spire/agent/trusted-certs.pem"
    trust_domain = "demo.example.org"
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path = "/etc/spire/agent/agent-key.pem"
            certificate_path = "/etc/spire/agent/agent-cert.pem"
        }
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/var/lib/spire/agent/.data"
        }
    }
    WorkloadAttestor "docker" {
        plugin_data {}
    }
}
